# This file has no relevance for production use, needed only for development.
# This file is needed to deactivate JUL console output. PAI5 does not configure/deactivate this anymore.
# While starting from IDE, we get duplicate log entries without this configuration, as logback is writing to console. 
handlers = 
.level = ALL

# Fix for CECJIRA-1662 - Launcher crashes when started from PDE
org.aspectj.weaver.level = CONFIG